pipeline {
  agent { dockerfile true 
  }
  stages {
    stage("Build") {
      steps {
        git 'https://github.com/islommuhammad/Exadel-Tasks.git'
        echo 'Hello world'
      }
    }
    // stage("Deploy") {
    //   steps {
    //     sshagent(credentials: ['Jenkins-server']) {
    //       sh '''
    //         ssh -o StrictHostKeyChecking=no -l root 172.17.0.1 docker ps -a
    //       '''
    //     }
    //   }
    // }
  }
}