pipeline {
  agent { dockerfile true }
  stages {
    stage("Build") {

    }
    // stage("Deploy") {
    //   steps {
    //     sshagent(credentials: ['Jenkins-server']) {
    //       sh '''
    //         ssh -o StrictHostKeyChecking=no -l root 172.17.0.1 docker ps -a
    //       '''
    //     }
    //   }
    // }
  }
}